client_config_backend: service
service_config:
  client_json_file_path: credentials.json
save_credentials: False
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
