name: Scheduled Hydrology Data Fetch

on:
  schedule:
    - cron: '15 4 * * *'  # Daily at 10:15 AM Nepal Time
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pydrive2 pyyaml

      - name: Inject credentials.json from secret
        run: echo '${{ secrets.GDRIVE_CREDENTIALS }}' > credentials.json

      - name: Create gdrive-config/settings.yaml
        run: |
          mkdir -p gdrive-config
          echo "client_config_backend: service" > gdrive-config/settings.yaml
          echo "service_config:" >> gdrive-config/settings.yaml
          echo "  client_json_file_path: credentials.json" >> gdrive-config/settings.yaml

      - name: Run hydrology data script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      - name: Upload CSV files to Google Drive
        env:
          FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python upload_to_gdrive.py
          