name: Scheduled Hydrology Data Fetch

on:
  schedule:
    - cron: '15 4 * * *'  # 10:15 a.m. Nepal Time
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pandas pydrive2

      - name: Save credentials.json
        run: |
          echo '${{ secrets.GDRIVE_CREDENTIALS }}' > credentials.json

      - name: Run hydrology data script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python main.py

      - name: Upload to Google Drive
        env:
          FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python <<EOF
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive
          import os

          gauth = GoogleAuth()
          gauth.LoadCredentialsFile("credentials.json")
          if gauth.credentials is None:
              gauth.LocalWebserverAuth()
          elif gauth.access_token_expired:
              gauth.Refresh()
          else:
              gauth.Authorize()
          gauth.SaveCredentialsFile("credentials.json")
          drive = GoogleDrive(gauth)

          for file_name in os.listdir("data"):
              if file_name.endswith(".csv"):
                  f = drive.CreateFile({'title': file_name, 'parents': [{"id": os.environ["FOLDER_ID"]}]})
                  f.SetContentFile(os.path.join("data", file_name))
                  f.Upload()
          EOF
